### ISSUE TITLE
Doesn't work on my installation.

### ISSUE THREAD

**Issue by shillshocked** [zeekay/soundcloud-cli#15]
`Traceback (most recent call last):
  File "/usr/bin/sc", line 2, in <module>
    from soundcloud_cli import cli
  File "/usr/lib/python3.9/site-packages/soundcloud_cli/__init__.py", line 3, in <module>
    import api
ModuleNotFoundError: No module named 'api'
`

**Comment by tsali** [comment]
I'm not involved with this project, however I recently had to re-install this on an new system I was building and a lot of the issues I was experiencing was because this project hasn't been converted to Python3 yet and your error message specifically mentions Python3. I would recommend uninstalling it and re-installing using pip2 instead of pip, and installing any additional modules you may be missing using pip2. Also I would highly recommend using this in a VENV.

```
pip2 install soundcloud-cli
pip2 install api
pip2 install six
```
