### ISSUE TITLE
does not upload

### ISSUE THREAD

**Issue by jmontiel** [zeekay/soundcloud-cli#9]
Hello, 

I just installed soundcloud-cli, but when I try to upload a file I get this error

root@redmine:~# sc 28.m4a 
Traceback (most recent call last):
  File "/usr/local/bin/sc", line 3, in <module>
    cli.main()
  File "/usr/local/lib/python2.7/dist-packages/soundcloud_cli/cli.py", line 216, in main
    args.command(args)
  File "/usr/local/lib/python2.7/dist-packages/soundcloud_cli/utils.py", line 37, in wrapper
    return f(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/soundcloud_cli/cli.py", line 139, in command_upload
    artwork=args.artwork)
  File "/usr/local/lib/python2.7/dist-packages/soundcloud_cli/api/upload.py", line 87, in upload
    (data, content_type) = requests.packages.urllib3.filepost.encode_multipart_formdata(data)
AttributeError: 'module' object has no attribute 'packages'

**Comment by jmontiel** [comment]
I found the problem is Ubuntu 14.04

http://stackoverflow.com/questions/28967785/attribute-error-installing-with-pip/30310206#30310206

Once I followed the instructions, it all worked properly

**Note**: read warning on link above

**Comment by zeekay** [comment]
Ah interesting! Thanks for sharing :)
